services:
  db:
    image: docker.io/library/postgres:16
    container_name: farm_postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  app:
    build: .
    container_name: farm_app
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+psycopg://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app:z
    command: uv run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: