"""initial master schema

Revision ID: 09c39f25bdc3
Revises:
Create Date: 2026-03-24 17:07:12.918050

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "09c39f25bdc3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "farm_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("txn_date", sa.Date(), nullable=False),
        sa.Column(
            "txn_type",
            sa.Enum("income", "expense", name="transactiontypeenum"),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.Enum(
                "livestock_sales",
                "byproduct_sales",
                "other_income",
                "feed",
                "medicine",
                "labor",
                "assets",
                "livestock_purchases",
                "maintenance",
                "utilities",
                "consumables",
                "transport",
                "other_expense",
                name="categoryenum",
            ),
            nullable=False,
        ),
        sa.Column(
            "item_description", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("qty", sa.Float(), nullable=False),
        sa.Column(
            "unit_of_measure",
            sa.Enum(
                "kg",
                "liters",
                "head",
                "month",
                "day",
                "job",
                "other",
                "ml",
                "grams",
                name="unitofmeasureenum",
            ),
            nullable=False,
        ),
        sa.Column("unit_price", sa.Float(), nullable=False),
        sa.Column("total_amount", sa.Float(), nullable=False),
        sa.Column("amount_paid", sa.Float(), nullable=False),
        sa.Column(
            "payment_status",
            sa.Enum("paid", "unpaid", "partially_paid", name="statusenum"),
            nullable=False,
        ),
        sa.Column("entity_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("reference_tag", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("remarks", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sa.Enum("ADMIN", "STAFF", name="userrole"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("farm_transactions")
    # ### end Alembic commands ###
