"""add inventory and livestock models

Revision ID: 2d893f9d07dd
Revises: cf919fb46671
Create Date: 2026-04-01 18:06:07.681310

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "2d893f9d07dd"
down_revision: Union[str, Sequence[str], None] = "cf919fb46671"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "livestock",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "tracking_type",
            sa.Enum("INDIVIDUAL", "BATCH", name="trackingtypeenum"),
            nullable=False,
        ),
        sa.Column("identifier", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "gender",
            sa.Enum("MALE", "FEMALE", "MIXED", name="genderenum"),
            nullable=False,
        ),
        sa.Column(
            "breed",
            sa.Enum(
                "LARGE_WHITE",
                "DUROC",
                "LANDRACE",
                "HAMPSHIRE",
                "CROSSBREED",
                "OTHER",
                name="pigbreedenum",
            ),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.Enum(
                "PIGLET",
                "WEANER",
                "GROWER",
                "FATTENER",
                "SOW",
                "BOAR",
                name="livestockcategoryenum",
            ),
            nullable=False,
        ),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "PREGNANT",
                "NURSING",
                "SICK",
                "SOLD",
                "DECEASED",
                name="livestockstatusenum",
            ),
            nullable=False,
        ),
        sa.Column("lineage_note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "supplyinventory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "category",
            sa.Enum("FEED", "MEDICINE", "EQUIPMENT", name="supplycategoryenum"),
            nullable=False,
        ),
        sa.Column("total_quantity", sa.Float(), nullable=False),
        sa.Column(
            "unit_of_measure", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "usage_metric",
            sa.Enum(
                "BOWLS", "ML", "KG", "GRAMS", "LITERS", "PIECES", name="usagemetricenum"
            ),
            nullable=False,
        ),
        sa.Column("conversion_rate", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inventorylog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("log_date", sa.DateTime(), nullable=False),
        sa.Column(
            "action_type",
            sa.Enum(
                "FED",
                "TREATED",
                "FARROWED",
                "DIED",
                "SOLD",
                "PROMOTED",
                "SPLIT",
                name="logactionenum",
            ),
            nullable=False,
        ),
        sa.Column("supply_used_id", sa.Integer(), nullable=True),
        sa.Column("livestock_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("amount_used", sa.Float(), nullable=True),
        sa.Column("remarks", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["livestock_id"],
            ["livestock.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supply_used_id"],
            ["supplyinventory.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("inventorylog")
    op.drop_table("supplyinventory")
    op.drop_table("livestock")
    # ### end Alembic commands ###
