"""upgrade category and status to strict enums

Revision ID: b96a573e5ac4
Revises: 80f3a9751690
Create Date: 2026-03-16 13:56:37.760863

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b96a573e5ac4"
down_revision: Union[str, Sequence[str], None] = "80f3a9751690"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transaction")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("txn_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("txn_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "item_description", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "qty",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "unit_price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "total_amount",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("payment_status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("remarks", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("transaction_pkey")),
    )
    # ### end Alembic commands ###
