"""rename table to farm_transactions

Revision ID: bfd38c6f8297
Revises: b96a573e5ac4
Create Date: 2026-03-16 14:11:34.278142

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "bfd38c6f8297"
down_revision: Union[str, Sequence[str], None] = "b96a573e5ac4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
