"""add user id to transaction

Revision ID: cf919fb46671
Revises: 09c39f25bdc3
Create Date: 2026-04-01 10:53:32.060767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf919fb46671'
down_revision: Union[str, Sequence[str], None] = '09c39f25bdc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm_transactions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'farm_transactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'farm_transactions', type_='foreignkey')
    op.drop_column('farm_transactions', 'user_id')
    # ### end Alembic commands ###
