"""implement farm_transaction and enums

Revision ID: e403293e8e87
Revises: bfd38c6f8297
Create Date: 2026-03-16 14:27:39.242970

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "e403293e8e87"
down_revision: Union[str, Sequence[str], None] = "bfd38c6f8297"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "farm_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("txn_date", sa.Date(), nullable=False),
        sa.Column("txn_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "feed",
                "medicine",
                "sales",
                "utilities",
                "rent",
                "property",
                "other",
                "labor",
                name="categoryenum",
            ),
            nullable=False,
        ),
        sa.Column(
            "item_description", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("qty", sa.Float(), nullable=False),
        sa.Column("unit_price", sa.Float(), nullable=False),
        sa.Column("total_amount", sa.Float(), nullable=False),
        sa.Column(
            "payment_status",
            sa.Enum("paid", "unpaid", "partially_paid", name="statusenum"),
            nullable=False,
        ),
        sa.Column("remarks", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("farm_transactions")
    # ### end Alembic commands ###
