from typing import Optional
from datetime import date
from sqlmodel import SQLModel, Field


class Transaction(SQLModel, table=True):
    # 1. Txn_ID: The primary key, auto-generated by the database
    id: Optional[int] = Field(default=None, primary_key=True)

    # 2. Date: A strict calendar date
    txn_date: date

    # 3. Type: e.g., "Income" or "Expense"
    txn_type: str

    # 4. Category: e.g., "Feed", "Medicine", "Sales"
    category: str

    # 5. Item_Description: What exactly was bought or sold
    item_description: str

    # 6. Qty: Using float because you might buy 50.5 kg of feed
    qty: float

    # 7. Unit_Price: The cost per unit
    unit_price: float

    # 8. Total_Amount: Total cost (Qty * Unit_Price)
    total_amount: float

    # 9. Payment_Status: e.g., "Paid", "Pending"
    payment_status: str

    # 10. Remarks: Optional extra notes. Allowed to be empty.
    remarks: Optional[str] = Field(default=None)
