name: CI

on:
  push:
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.14'
    - name: Install the latest version of uv and set the python version
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
    - run: uv sync
    - run: uv run ruff check .
    - run: uv run ruff format --check .

